"""The Reinvent uq sampling module"""

__all__ = ["Reinvent_UQSampler"]
import logging

from rdkit import Chem

from .sampler import Sampler, remove_duplicate_sequences, validate_smiles
from ...models.model_factory.sample_batch import SampleBatch

logger = logging.getLogger(__name__)


class Reinvent_UQSampler(Sampler):
    """Carry out UQ sampling with Reinvent"""

    def sample(self, n_samples: int, input_length: int, input_smilies = None) -> SampleBatch:
        """
        Draw UQ samples.

        Parameters
        ----------
        n_samples : integer
            How many samples to draw per (partial) input sequence

        input_length : integer
            The length of a partial input sequence

        Returns
        -------
        SampleBatch
            Container to hold the data returned by the adapter 
            .sample() methods.

       """
        sampled = self.model.sample(self.batch_size, n_samples, input_length, input_smilies)
        # sampled.items1 = None  # expected in sampling runmode

        if self.unique_sequences:
            sampled = remove_duplicate_sequences(sampled, is_reinvent=True)

        mols = [
            Chem.MolFromSmiles(smiles, sanitize=False) if smiles else None
            for smiles in sampled.output
        ]

        # sampled.output contains the smiles generated by the RNN
        sampled.smilies, sampled.states = validate_smiles(mols, sampled.output)
        # sampled.smilies are the canonicalized smiles that will be written to disk

        return sampled
