"""The Reinvent sampling module"""

__all__ = ["ReinventSampler"]
import logging

from rdkit import Chem

from .sampler import Sampler, remove_duplicate_sequences, validate_smiles
from ...models.model_factory.sample_batch import SampleBatch

logger = logging.getLogger(__name__)


class ReinventSampler(Sampler):
    """Carry out sampling with Reinvent"""

    def sample(self, dummy) -> SampleBatch:
        """Samples the Reinvent model for the given number of SMILES

        :param dummy: Reinvent does not need SMILES input
        :returns: SampleBatch
        """

        sampled = self.model.sample(self.batch_size)
        sampled.items1 = None  # expected in sampling runmode
        print('FOOOOOOOOOOOOOOO')
        if self.unique_sequences:
            sampled = remove_duplicate_sequences(sampled, is_reinvent=True)

        mols = [
            Chem.MolFromSmiles(smiles, sanitize=False) if smiles else None
            for smiles in sampled.output
        ]

        # sampled.output contains the smiles generated by the RNN
        sampled.smilies, sampled.states = validate_smiles(mols, sampled.output)
        # sampled.smilies are the canonicalized smiles that will be written to disk

        # self.model.model.sample_given_X(10)

        return sampled
