# REINVENT4 TOML input example for scoring
#

run_type = "scoring"
device = "cpu"
json_out_config = "_scoring.json"  # write this TOML to JSON

[parameters]

smiles_file = "test.smi"  # SMILES file with 1 molecule per line
output_csv = "scoring.csv"  # name of output CSV to write, optional


[scoring]

parallel = false  # do not run scoring components in parallel

[[scoring.component]]

[[scoring.component.MolecularWeight.endpoint]]
name = "Molecular weight"  # user chosen name for output
weight = 1.0  # weight to fine-tune the relevance of this component
